add components diagram
inzOprogramowaniaUZ/violetumleditor pull request #27
Opened 2017-02-14 18:04 UTC by Unforced

2017-02-14 18:48 UTC, nifrez reviewed
Remove empty tests, and useless javadocs

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/src/main/java/com/horstmann/violet/product/diagram/component/node/ComponentNode.java
> +     * @return Tooltip string.
Useless javadoc

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/src/main/java/com/horstmann/violet/product/diagram/component/node/ComponentNode.java
> +     * Gets connection point.
Useless javadoc / not completed javadoc

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/src/main/java/com/horstmann/violet/product/diagram/component/node/ComponentNode.java
> +     * @param edge
useless javadoc

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/src/main/java/com/horstmann/violet/product/diagram/component/node/ComponentNode.java
> +     * Gets the text property value.
useless javadoc

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
??????????????????

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
?????????????????

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
?????????????????

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
?????????????????

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
?????????????????

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
?????????????????

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
?????????????????

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
?????????????????

2017-02-14 18:48 UTC, nifrez commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
?????????????????

2017-02-14 19:12 UTC, abizukojc commented on violetplugin-componentdiagram/src/main/java/com/horstmann/violet/product/diagram/component/ComponentDiagramGraph.java
> +public class ComponentDiagramGraph extends AbstractGraph {
Bad formatting. The bracket { should be under the class/method header. Correct it everywhere.

2017-02-14 19:15 UTC, abizukojc commented on pom.xml
>      <!-- Modules 'exe' and 'web' are commented out because they're causing problems during project build-->
This block of comments is useless now.

2017-02-14 19:32 UTC, bartoszsledz commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
xDDDDDDDDDDDDDDDDDDDDDDDDDDD no przeciez przechodzą 🥇

2017-02-14 19:36 UTC, Unforced commented on violetplugin-componentdiagram/test/com/horstmann/violet/product/diagram/component/node/ComponentNodeTest.java
> +
no jak to nie ma testów?

2017-02-14 21:22 UTC, NdV66 commented on violetplugin-componentdiagram/src/main/java/com/horstmann/violet/product/diagram/component/node/ComponentNode.java
> +            return true;
I don't like double returns in one method.
It should be better, if you change it to one return.
boolean result = false;
if(...) {
result = true;
}
return result;

2017-02-14 21:24 UTC, NdV66 commented
@RoughTomato @abizukojc 

It **ISN'T** able to be merge yet 👎 
We'll waiting for changes.

2017-02-14 21:24 UTC, abizukojc reviewed
Re-check the comments

2017-02-15 15:48 UTC, orchowski approved these changes

2017-02-15 16:08 UTC, abizukojc requested changes
Check the comments once again.

2017-02-15 16:59 UTC, NdV66 commented
@abizukojc please review

2017-02-15 17:33 UTC, abizukojc requested changes
There are still comments in this PR. Fix commented places, or reply the comments,

2017-02-15 21:40 UTC, RoughTomato commented
outdated files ../../../../ComponentNodeTest.java might cause compatibility problems. Please update to current HEAD~.

2017-02-16 12:45 UTC, NdV66 commented
Update it.

2017-02-16 17:17 UTC, abizukojc approved these changes

2017-02-16 17:58 UTC, merged