SpellChecker Sebastian Podgórski
inzOprogramowaniaUZ/violetumleditor pull request #38
Opened 2017-02-16 16:22 UTC by wenaro

2017-02-16 16:40 UTC, orchowski approved these changes

2017-02-16 17:02 UTC, orchowski approved these changes

2017-02-16 17:05 UTC, abizukojc requested changes

2017-02-16 17:05 UTC, abizukojc commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/behavior/EditSelectedDuplicateBehavior.java
> +    private final String STEREOTYPE_ENDING = "�";
Use unicode for this character (\uXXXX format)

2017-02-16 17:05 UTC, abizukojc commented on violet-framework/src/main/java/com/horstmann/violet/workspace/spellchecker/SpellChecker.java
> + * @author Sebastian Podgorski
This should be removed

2017-02-16 17:21 UTC, abizukojc commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/behavior/EditSelectedDuplicateBehavior.java
> +    private final String STEREOTYPE_ENDING = "»";
Write this character in the unicode format e.g \uXXXX
https://unicode-table.com/en/

2017-02-16 17:24 UTC, wenaro commented on violet-framework/src/main/java/com/horstmann/violet/workspace/spellchecker/SpellChecker.java
> + * @author Sebastian Podgorski
I think it isn't the only one class with @author annotation, so please check all classes for this annotation

2017-02-16 17:25 UTC, abizukojc approved these changes

2017-02-16 17:28 UTC, wenaro commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/behavior/EditSelectedDuplicateBehavior.java
> +    private final String STEREOTYPE_ENDING = "�";
This is not my change, please talk to author of this class

2017-02-16 17:46 UTC, wenaro commented on violet-framework/src/main/java/com/horstmann/violet/workspace/spellchecker/SpellChecker.java
> + * @author Sebastian Podgorski
Done

2017-02-16 18:43 UTC, RoughTomato commented
conflicts need to be resolved before merging

2017-02-16 18:48 UTC, RoughTomato requested changes
Merge conflicts need to be resolved before merging can be done.

2017-02-16 20:49 UTC, abizukojc requested changes
This PR shouldn't be merged now. There are too much files modified and most next PRs will have conflicts after this merge.

2017-02-18 18:50 UTC, NdV66 requested changes
I agree  with @abizukojc

2017-02-19 15:11 UTC, orchowski requested changes
Conflicts again. 
Resolve it, or (which will be much better) remove this useless changes, because you're conflicting with everything in this case.

2017-02-19 18:00 UTC, wenaro commented
Optimize imports is needed, because it is better to have imported one package e.g java.awt.Color
then all packages from library like java.awt.*. Conflicts are resolved on a constant basis

2017-02-21 17:21 UTC, orchowski approved these changes

2017-02-21 17:28 UTC, orchowski commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/behavior/EditSelectedBehavior.java
> +        nodeName = nodeName.replaceAll("<html><font size=\\+1>", "").replaceAll("</font><html>", "");
coding UTF8

2017-02-21 17:30 UTC, abizukojc requested changes
Fix encoding problems

2017-02-21 17:30 UTC, abizukojc commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/behavior/EditSelectedBehavior.java
> +        nodeName = nodeName.replaceAll("<html><center>�interface�</center> <font size=\\+1>", "");
for chars << and >> use unicodes

2017-02-21 17:43 UTC, orchowski approved these changes

2017-02-21 17:47 UTC, abizukojc commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/behavior/EditSelectedBehavior.java
> +        nodeName = nodeName.replaceAll("<html><center>«enumeration»</center> <font size=\\+1>", "");
You should use Unicode notation (\uXXXX)

2017-02-21 17:59 UTC, abizukojc approved these changes

2017-02-21 17:59 UTC, merged