Autosave MDZ, MFI, MMR, KFL, HMA
inzOprogramowaniaUZ/violetumleditor pull request #39
Opened 2017-02-16 17:47 UTC by regit66

2017-02-16 18:28 UTC, abizukojc requested changes
You have still conflicts in PR.

2017-02-16 18:32 UTC, regit66 commented
Yes, i know :)

2017-02-16 19:08 UTC, abizukojc commented
Build on Travis failed

2017-02-16 19:19 UTC, abizukojc commented
You have new conflicts

2017-02-16 19:58 UTC, orchowski requested changes

2017-02-16 19:58 UTC, orchowski commented on config.properties
> +autosave_path=D\:\\
I think it's wrong. My notebook have only c: partition and... what about linux users?

2017-02-16 19:58 UTC, orchowski commented on violetproduct-swing/src/test/java/com/horstmann/violet/application/autosave/AutosaveSettingsTest.java
> +		String expectedResult = "c:\\ff";
path C:\\ 
i think that on linux this tests will not pass

2017-02-16 20:08 UTC, regit66 commented on config.properties
> +autosave_path=D\:\\
yes , you have right

2017-02-16 20:09 UTC, regit66 commented
now should work

2017-02-16 20:17 UTC, orchowski commented on config.properties
> +autosave_path=D\:\\
System.getProperty("user.home")   <- user home directory which is system independent

2017-02-16 20:34 UTC, abizukojc requested changes
Check the comments

2017-02-16 20:34 UTC, abizukojc commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/autosave/AutoSaveRecover_fr.properties
> +dialog.autosave.title=Autosave r�cup�rer
For national chars use unicodes (\uXXXX)

2017-02-16 20:34 UTC, abizukojc commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/autosave/AutoSaveRecover_fr.properties
> +dialog.autosave.recover=Restaurer projet non enregistr�
Up

2017-02-16 20:34 UTC, abizukojc commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/autosave/IAutoSave.java
> + * @author Marta Mrugalska
It should be removed

2017-02-16 20:34 UTC, abizukojc commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/gui/SettingsDialog.java
> + * @author Marta Mrugalska
See above

2017-02-16 20:34 UTC, abizukojc commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/gui/SettingsDialog_de.properties
> +dialog.button.selectPathText=Pfad ausw�hlen�
Encoding in this file - see above

2017-02-16 20:34 UTC, abizukojc commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/gui/SettingsDialog_fr.properties
> +dialog.label.saveDirectoryText=Enregistrer le r�pertoire
Up

2017-02-16 21:38 UTC, abizukojc commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/gui/SettingsDialog.java
> + * @author Marta Mrugalska
What with this ?

2017-02-16 21:41 UTC, abizukojc approved these changes

2017-02-18 15:54 UTC, orchowski approved these changes

2017-02-18 16:19 UTC, merged