Added switching method which show or hide methods and variables.
inzOprogramowaniaUZ/violetumleditor pull request #44
Opened 2017-02-16 20:11 UTC by MeNana

Added switching method which show or hide methods and variables.

2017-02-16 21:36 UTC, abizukojc requested changes

2017-02-16 21:36 UTC, abizukojc commented on violetplugin-classdiagram/src/main/java/com/horstmann/violet/product/diagram/classes/node/ClassNode.java
>      private static final String ABSTRACT = "«abstract»";
Change the << and >> characters to unicods.

2017-02-16 21:36 UTC, abizukojc commented on violetplugin-classdiagram/src/main/java/com/horstmann/violet/product/diagram/classes/node/InterfaceNode.java
>      private static final String STATIC = "<<static>>";
Shoudln't it be the special characters « » ? If i have right, then use unicodes.

2017-02-16 21:36 UTC, abizukojc commented on violetplugin-classdiagram/src/main/java/com/horstmann/violet/product/diagram/classes/node/ClassNode.java
>      private static final String STATIC = "<<static>>";
Shoudln't it be the special characters « » ? If i have right, then use unicodes.

2017-02-16 22:34 UTC, MeNana commented
I just added unicodes.

2017-02-17 14:15 UTC, abizukojc commented
Resolve conflicts

2017-02-18 13:48 UTC, abizukojc approved these changes

2017-02-18 18:49 UTC, NdV66 reviewed
Fix or reply

2017-02-18 18:49 UTC, NdV66 commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/behavior/ShowMenuOnRightClickBehavior.java
> +        aPopupMenu.add(show);
why the nme of variable start wit "a"? :)

2017-02-18 18:49 UTC, NdV66 commented on violetplugin-classdiagram/src/main/java/com/horstmann/violet/product/diagram/classes/node/ClassNode.java
> +	private boolean VISIBLE_METHODS_AND_ATRIBUTES = true;
whitespaces

2017-02-18 18:49 UTC, NdV66 commented on violetplugin-classdiagram/src/main/java/com/horstmann/violet/product/diagram/classes/node/InterfaceNode.java
> +	private boolean VISIBLE_METHODS_AND_ATRIBUTES = true;
why whitespaces

2017-02-18 20:43 UTC, MeNana commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/behavior/ShowMenuOnRightClickBehavior.java
> +        aPopupMenu.add(show);
because it was like that(I only add new option) and looking good.

2017-02-19 09:12 UTC, NdV66 requested changes
Conflicts

2017-02-19 15:09 UTC, orchowski requested changes
Resolve conflicts

2017-02-20 08:11 UTC, MeNana commented
solved

2017-02-20 16:56 UTC, abizukojc requested changes
Build on Travis failed. Fix it.

2017-02-21 13:02 UTC, MeNana commented
FIXED

2017-02-21 14:50 UTC, abizukojc approved these changes

2017-02-21 15:20 UTC, NdV66 approved these changes

2017-02-21 15:55 UTC, merged