Kupniewski add opening window
inzOprogramowaniaUZ/violetumleditor pull request #47
Opened 2017-02-17 10:16 UTC by lormniczek

Poprawiłem błędy z nullami i dodałem nazwy do propertiesów, działa we wszystkich językach od violeta.

2017-02-17 14:14 UTC, abizukojc requested changes
You have conflicts. Fix it.

2017-02-17 15:06 UTC, abizukojc requested changes

2017-02-17 15:06 UTC, abizukojc commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/gui/SplashFrame.java
> + * @author Maciej Kupniewski
Remove this

2017-02-17 15:06 UTC, abizukojc commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/gui/SplashFrame_fr.properties
> +nameBtnActivityDiagram=Diagramme d'activit�
Use unicode here

2017-02-17 15:12 UTC, bartoszsledz commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/gui/SplashFrame.java
> +        frame.setTitle("Okno Powitalne");
use properties file.. pl,eng,fr,ger

2017-02-17 15:13 UTC, bartoszsledz commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/gui/SplashFrame_fr.properties
> +nameBtnActivityDiagram=Diagramme d'activit�
/u

2017-02-17 15:16 UTC, bartoszsledz commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/gui/SplashFrame.java
> +
this not working with feature 'settings language in project'.. always shows in polish, try fix it

2017-02-17 15:18 UTC, bartoszsledz commented on violetproduct-swing/src/main/java/com/horstmann/violet/application/gui/SplashFrame.java
> +
this not working with feature 'settings language in project'.. always shows in polish, try fix it

2017-02-17 18:54 UTC, orchowski requested changes
Resolve conflicts

2017-02-18 13:04 UTC, abizukojc requested changes
It's ok, but resolve conflicts first.

2017-02-18 13:30 UTC, abizukojc approved these changes

2017-02-18 15:09 UTC, orchowski approved these changes

2017-02-18 15:38 UTC, merged