Violet 19
inzOprogramowaniaUZ/violetumleditor pull request #75
Opened 2017-02-22 20:38 UTC by CezaryH257

If you want to delete elements (such as class, interface etc.), you must confirm that deletion by clicking yes or no in confirmation window.

2017-02-22 20:49 UTC, NdV66 reviewed
Fix or reply

2017-02-22 20:49 UTC, NdV66 commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/EditorPart.java
> +    	int reply = JOptionPane.showConfirmDialog(null, deleteDialogText, null, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
maybe 
return JOptionPane.showConfirmDialog(null, deleteDialogText, null, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_NO_OPTION

2017-02-22 20:52 UTC, abizukojc commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/EditorPart.java
> +    private String deleteDialogText = "Delete selected elements?";
Why is this hard-coded ? You should use properties for all languages available in VioletUML

2017-02-22 21:08 UTC, orchowski commented on violet-framework/src/main/java/com/horstmann/violet/workspace/editorpart/EditorPart.java
> +    private String deleteDialogText = "Delete selected elements?";
I agree with that

2017-02-22 22:38 UTC, RoughTomato requested changes
Fix already commented functionalities

2021-02-12 08:30 UTC, orchowski commented
Looks good to me. I didn't have time to review the changes. But I see that it's not too late :)

2021-02-12 08:33 UTC, orchowski approved these changes

2021-02-12 08:34 UTC, Peroniada commented
Please squash commits to make it easier to review :)

2021-02-12 08:38 UTC, Peroniada approved these changes

2021-02-15 23:38 UTC, closed without merging